### ISSUE TITLE
[error in line 400]

### ISSUE THREAD

**Issue by jonarmin** [btminzon/bandcombination#8]
Hi Breno how are you?

I used this program to get the comnination supported in some device, but now show the error in line 400 could you help to check? I used QCAT to get info of UEcapability
[uecapability_235M.txt](https://github.com/btminzon/bandcombination/files/9152523/uecapability_235M.txt)
.

**Comment by btminzon** [comment]
Just tested with latest version and Python 3.10, in Pycharm 2022.2, and works fine. Can you please test again?
